AWSTemplateFormatVersion: '2010-09-09'
Description: App Runner Service to deploy Movenet Backend from ECR

Parameters:
  ImageUri:    { Type: String }
  RoleArn:     { Type: String }  # (for ECR pull)
  AppEnv:      { Type: String, Default: prod }
  AppName:     { Type: String, Default: movenet-backend-service }

Resources:
  AppRunnerInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AppName}-InstanceRole"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: apprunner.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3UploadPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:PutObjectAcl
                Resource:
                  - !Sub "arn:aws:s3:::${AWS::AccountId}-${AppEnv}-movenet-logs/*"

  MovenetAppRunnerService:
    Type: AWS::AppRunner::Service
    Properties:
      ServiceName: !Ref AppName
      SourceConfiguration:
        ImageRepository:
          ImageRepositoryType: ECR
          ImageIdentifier: !Ref ImageUri
          ImageConfiguration:
            Port: "8080"
            RuntimeEnvironmentVariables:
              - Name: APP_ENV
                Value: !Ref AppEnv
              - Name: AWS_REGION
                Value: !Ref AWS::Region
        AuthenticationConfiguration:
          AccessRoleArn: !Ref RoleArn     # your ECR-pull role
        AutoDeploymentsEnabled: true

      InstanceConfiguration:
        Cpu:             "2 vCPU"
        Memory:          "4 GB"
        InstanceRoleArn: !GetAtt AppRunnerInstanceRole.Arn
